### ISSUE TITLE
Broken SSR example

### ISSUE THREAD

**Issue by zloidemon** [tris-foundation/examples#10]
If you will fast stop/start application you can get this error each 1-2 run an application

```
[info] server at http://0.0.0.0:8080 started
Received signal 11 SEGV_MAPERR 0000c8b62b9e

==== C stack trace ===============================

 [0x00010ce36324]
 [0x7fff50c87f5a]
 [0x7ffee3eaf9f0]
 [0x7fff4fd52c51]
 [0x7fff4fd55e26]
 [0x7fff4fd55914]
 [0x00010e2dfdf4]
 [0x00010dfcccfd]
 [0x00010bda51af]
 [0x00010bda1a31]
 [0x00010bda0362]
 [0x00010bd96bc1]
 [0x00010bd96ca9]
 [0x00010bfc77c0]
 [0x7fff50979015]
[end of stack trace]
make: *** [run] Segmentation fault: 11
```

**Comment by tonyfreeman** [comment]
Yeah, this is an issue on macOS and I don't know how to fix it yet. The module works fine on Linux. Let's hope a newer version of node wouldn't have this issue. I'm going to investigate this a bit later.

**Comment by tonyfreeman** [comment]
I've updated Node.js to 10.1.0 and the issue is gone, please check it out.
