### ISSUE TITLE
Cant Build SSR Example

### ISSUE THREAD

**Issue by stunjiturner** [tris-foundation/examples#13]
/Users/stunjiturner/Downloads/examples-master/server-side-rendering/.build/checkouts/crypto.git-1258857006649115742/Sources/Crypto/UInt24.swift:241:1: error: type 'UInt24' does not conform to protocol 'UnsignedInteger'
extension UInt24: FixedWidthInteger {

**Comment by stunjiturner** [comment]
/Users/stunjiturner/Downloads/examples-master/server-side-rendering/.build/checkouts/crypto.git-1258857006649115742/Sources/Crypto/UInt24.swift:241:1: error: type 'UInt24' does not conform to protocol 'UnsignedInteger'

**Comment by stunjiturner** [comment]
same error as before, using swift build -Xcc -I/usr/local/include/node -Xlinker /usr/local/lib/libnode.so.57

**Comment by tonyfreeman** [comment]
@stunjiturner you have to run `swift package update` first

**Comment by stunjiturner** [comment]
swift build -Xcc -I/usr/local/include/node -Xlinker /usr/local/lib/libnode.64.dylib this command works, but swift build -Xcc -I/usr/local/include/node -Xlinker /usr/local/lib/libnode.so.57 produces 

error:
ld: file not found: /usr/local/lib/libnode.so.57

and .build/debug/main command produces

error:
-bash: .build/debug/main: No such file or directory
