### ISSUE TITLE
Swift module from lua

### ISSUE THREAD

**Issue by mogol** [tris-foundation/examples#7]
Hi, thanks for great job. 
Can you add examples how to call module from lua ? I tried tarantool-module example. It works from connector , but it shows error for calling helloSwift from tarantool.lua.

**Comment by mogol** [comment]
Found solution here https://github.com/tarantool/tarantool/wiki/Recipes-Modules#cc-module

**Comment by tonyfreeman** [comment]
Hi! Sorry for the delay.
Yeah, swift code wont be much different except some tricks with @_silgen. 
But you right, i should add an example for swift. Thank you!

**Comment by mogol** [comment]
Hey, thanks for reply. Actually I still have a problem. That way gives me only first "exported" function. I failed to export more than one function. Seems some issues with 'luaL_register'

**Comment by mogol** [comment]
I made example. I managed to register functions, but they don't have right names.

```
tarantool> swift = require('SwiftTarantoolModule')
---
...
tarantool> swift
---
- '': 'function: 0x0f39b038'
  !!binary CPFBE/l/: 'function: 0x0f39b060'
...
```

```swift
import MessagePack
import TarantoolModule
import CTarantool

@_silgen_name("luaopen_SwiftTarantoolModule")
public func open(L: OpaquePointer!) -> Int32 {
    let regs = [
        luaL_Reg(name: "func1".cString(using: .ascii), func: func1),
        luaL_Reg(name: "func2".cString(using: .ascii), func: func2),
        luaL_Reg(name: nil, func: nil)
    ]
    _luaL_register(L, "SwiftTarantoolModule", regs);
    return 1
}

public func func1(L: OpaquePointer?) -> Int32 {
    print("func1")

    return 0
}

public func func2(L: OpaquePointer?) -> Int32 {
    print("func2")
    
    return 0
}
```

**Comment by mogol** [comment]
Heh, seems I did wrong with Swift String - Cstring interop.
Now it woks as I want. Would be nice to add such examples

```swift
import MessagePack
import TarantoolModule
import CTarantool

@_silgen_name("luaopen_SwiftTarantoolModule")
public func open(L: OpaquePointer!) -> Int32 {
    reg(L, "func1", func1);
    reg(L, "func2", func2);
    
    return 1
}

private func reg(_ L: OpaquePointer!,_ name: String,_ function: @escaping CTarantool.lua_CFunction){
    name.withCString{ ptr in
        let regs = [
            luaL_Reg(name: ptr, func: function),
            luaL_Reg(name: nil, func: nil)
        ]
        _luaL_register(L, "SwiftTarantoolModule", regs);
    }
}

public func func1(L: OpaquePointer?) -> Int32 {
    print("func1")
    return 0
}

public func func2(L: OpaquePointer?) -> Int32 {
    print("func2")
    return 0
}
```

**Comment by tonyfreeman** [comment]
I've added an example. Thank you for your contribution!

**Comment by tonyfreeman** [comment]
I found that luaL_register was deprecated, so the correct way is to push a table and add set your functions there https://github.com/tris-foundation/examples/commit/e5f74dbbc48aad133b8aae3f7a697d0d9341a2c5 https://github.com/tris-foundation/examples/commit/a1b1186447af1dbba68212a38dbd7f6ceb1aaa4b
